on:
  issues:
    types: [opened]
jobs:
  titlePrefixCheck:
    runs-on: ubuntu-latest
    steps:
      - if: startsWith(github.event.issue.title, 'ABC-') != 'true'
        name: Close Issue
        
        uses: peter-evans/close-issue@v3
      #  token: ${{secrets.TOKEN_PAT}}
        with:
          comment: |
            Issue title must start with 'ABC-'.
            Auto-closing this issue.
